/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_carreras_deportivasfinal.GUI.Corredores;

import gestion_carreras_deportivasfinal.DTO.Corredor;
import gestion_carreras_deportivasfinal.DTO.LogicaNegocioCorredor;
import gestion_carreras_deportivasfinal.GUI.Carreras.CarreraCrear;
import gestion_carreras_deportivasfinal.GUI.Carreras.CarreraTabla;
import gestion_carreras_deportivasfinal.GUI.PantallaPrincipal;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class CorredorCrear extends javax.swing.JDialog {
 
    
    //CREAMOS LAS LOGICAS DE NEGOCIO
    private LogicaNegocioCorredor logicaNegocioCorredor;
    
    
    /**
     * Creates new form CorredorCrear
     */
    public CorredorCrear(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreCorredor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDNICorredor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonCrearCorredor = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jSpinnerFecha_nacCorredor = new javax.swing.JSpinner();
        jTextFieldTelefonoCorredor = new javax.swing.JTextField();
        jTextFieldDireccionCorredor = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTABLA_CARRERAS = new javax.swing.JMenu();
        jMenuIrTablaCarreras = new javax.swing.JMenuItem();
        jMenuItemCrearCarrera = new javax.swing.JMenuItem();
        jMenuTABLA_CORREDORES = new javax.swing.JMenu();
        jMenuIrTablaCorredores = new javax.swing.JMenuItem();
        jMenuCrearCorredor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del Corredor");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DNI");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha de Nacimiento");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Direccion");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");

        jButtonCrearCorredor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCrearCorredor.setText("Crear Corredor");
        jButtonCrearCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCorredorActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jSpinnerFecha_nacCorredor.setModel(new javax.swing.SpinnerDateModel());

        jMenuTABLA_CARRERAS.setText("Tabla De Carreras");

        jMenuIrTablaCarreras.setText("Ir a Tabla de Carreras");
        jMenuIrTablaCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIrTablaCarrerasActionPerformed(evt);
            }
        });
        jMenuTABLA_CARRERAS.add(jMenuIrTablaCarreras);

        jMenuItemCrearCarrera.setText("Crear Carrera");
        jMenuItemCrearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearCarreraActionPerformed(evt);
            }
        });
        jMenuTABLA_CARRERAS.add(jMenuItemCrearCarrera);

        jMenuBar1.add(jMenuTABLA_CARRERAS);

        jMenuTABLA_CORREDORES.setText("Tabla De Corredores");

        jMenuIrTablaCorredores.setText("Ir a la Tabla de Corredores");
        jMenuIrTablaCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIrTablaCorredoresActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuIrTablaCorredores);

        jMenuCrearCorredor.setText("Crear Corredor");
        jMenuCrearCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCrearCorredorActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuCrearCorredor);

        jMenuBar1.add(jMenuTABLA_CORREDORES);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDNICorredor)
                            .addComponent(jTextFieldNombreCorredor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerFecha_nacCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 188, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jTextFieldTelefonoCorredor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDireccionCorredor)))
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jButtonCrearCorredor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVolver)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDNICorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerFecha_nacCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDireccionCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefonoCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrearCorredor)
                    .addComponent(jButtonVolver))
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //VALIDACION
    private boolean validarFormulario(){
        String nombre = jTextFieldNombreCorredor.getText();
        String DNI = jTextFieldDNICorredor.getText();
        String direccion = jTextFieldDireccionCorredor.getText();
        String telefono = jTextFieldTelefonoCorredor.getText();
        Date fecha = (Date)jSpinnerFecha_nacCorredor.getValue();
        
        if(nombre == null || DNI == null || direccion == null || telefono == null || fecha == null ||
              "".equals(nombre) || "".equals(DNI)|| "".equals(direccion)|| "".equals(telefono) || "".equals(fecha)){
               JOptionPane.showMessageDialog(this, "No puede quedar vacio ningun campo", "Error", JOptionPane.ERROR_MESSAGE);
                       return false;
        }
        return true;
    }
    
    //ACCIONES
    
    public void CrearCorredor(){
        if(validarFormulario()){
            String nombre = jTextFieldNombreCorredor.getText();
            String DNI = jTextFieldDNICorredor.getText();
            Date fecha = (Date)jSpinnerFecha_nacCorredor.getValue();
            String direccion = jTextFieldDireccionCorredor.getText();
            String telefono = jTextFieldTelefonoCorredor.getText();
            
            Corredor corredor = new Corredor(nombre, DNI, fecha, direccion, telefono);
            logicaNegocioCorredor.aniadirCorredor(corredor);

            setVisible(false);
        }
    }
    private void jMenuCrearCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCrearCorredorActionPerformed
        CrearCorredor();
    }//GEN-LAST:event_jMenuCrearCorredorActionPerformed

    private void jButtonCrearCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCorredorActionPerformed
        CrearCorredor();
    }//GEN-LAST:event_jButtonCrearCorredorActionPerformed

    private void jMenuIrTablaCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIrTablaCarrerasActionPerformed
        List<Corredor> listaCorredor = logicaNegocioCorredor.getListaCorredor();
        
        if(listaCorredor.size()==0 || listaCorredor.get(0).getNombre()==""){
            JOptionPane.showMessageDialog(this, "No puedes crear una carrera sin corredores", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            CarreraTabla carreraTabla = new CarreraTabla(new javax.swing.JFrame(), true);
            carreraTabla.setVisible(true);
        }


    }//GEN-LAST:event_jMenuIrTablaCarrerasActionPerformed

    private void jMenuItemCrearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearCarreraActionPerformed
          List<Corredor> listaCorredor = logicaNegocioCorredor.getListaCorredor();
        
        if(listaCorredor.size()==0 || listaCorredor.get(0).getNombre()==""){
            JOptionPane.showMessageDialog(this, "No puedes crear una carrera sin corredores", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            CarreraCrear carreraCrear = new CarreraCrear(new javax.swing.JFrame(), true);
            carreraCrear.setVisible(true);
        }

     
    }//GEN-LAST:event_jMenuItemCrearCarreraActionPerformed

    private void jMenuIrTablaCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIrTablaCorredoresActionPerformed
       CorredorTabla corredorTabla = new CorredorTabla(new javax.swing.JFrame(), true);
       corredorTabla.setVisible(true);
    }//GEN-LAST:event_jMenuIrTablaCorredoresActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorredorCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorredorCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorredorCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorredorCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CorredorCrear dialog = new CorredorCrear(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCrearCorredor;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCrearCorredor;
    private javax.swing.JMenuItem jMenuIrTablaCarreras;
    private javax.swing.JMenuItem jMenuIrTablaCorredores;
    private javax.swing.JMenuItem jMenuItemCrearCarrera;
    private javax.swing.JMenu jMenuTABLA_CARRERAS;
    private javax.swing.JMenu jMenuTABLA_CORREDORES;
    private javax.swing.JSpinner jSpinnerFecha_nacCorredor;
    private javax.swing.JTextField jTextFieldDNICorredor;
    private javax.swing.JTextField jTextFieldDireccionCorredor;
    private javax.swing.JTextField jTextFieldNombreCorredor;
    private javax.swing.JTextField jTextFieldTelefonoCorredor;
    // End of variables declaration//GEN-END:variables
}
