/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_carreras_deportivasfinal.GUI.Corredores;

import gestion_carreras_deportivasfinal.DTO.Corredor;
import gestion_carreras_deportivasfinal.DTO.LogicaNegocioCorredor;
import gestion_carreras_deportivasfinal.GUI.Carreras.CarreraCrear;
import gestion_carreras_deportivasfinal.GUI.Carreras.CarreraTabla;
import gestion_carreras_deportivasfinal.GUI.PantallaPrincipal;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class CorredorModificar extends javax.swing.JDialog {


    
    //CREAMOS LAS LOGICAS DE NEGOCIO
    private LogicaNegocioCorredor logicaNegocioCorredor;
    
    private String idAnterior="";
    
    /**
     * Creates new form CorredorModificar
     */
    public CorredorModificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonVolver = new javax.swing.JButton();
        jButtonModificarCorredor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTelefonoCorredor = new javax.swing.JTextField();
        jSpinnerFecha_nacCorredor = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDNICorredor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNombreCorredor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldDireccionCorredor = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTABLA_CARRERAS = new javax.swing.JMenu();
        jMenuIrTablaCarreras = new javax.swing.JMenuItem();
        jMenuIrCrearCarrera = new javax.swing.JMenuItem();
        jMenuTABLA_CORREDORES = new javax.swing.JMenu();
        jMenuIrTablaCorredores = new javax.swing.JMenuItem();
        jMenuIrCrearCorredor = new javax.swing.JMenuItem();
        jMenuItemModificarCorredor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonModificarCorredor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonModificarCorredor.setText("Modificar Corredor");
        jButtonModificarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarCorredorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre del Corredor");

        jSpinnerFecha_nacCorredor.setModel(new javax.swing.SpinnerDateModel());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Direccion");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Fecha de Nacimiento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DNI");

        jMenuTABLA_CARRERAS.setText("Tabla De Carreras");

        jMenuIrTablaCarreras.setText("Ir a Tabla de Carreras");
        jMenuIrTablaCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIrTablaCarrerasActionPerformed(evt);
            }
        });
        jMenuTABLA_CARRERAS.add(jMenuIrTablaCarreras);

        jMenuIrCrearCarrera.setText("Crear una Carrera");
        jMenuIrCrearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIrCrearCarreraActionPerformed(evt);
            }
        });
        jMenuTABLA_CARRERAS.add(jMenuIrCrearCarrera);

        jMenuBar1.add(jMenuTABLA_CARRERAS);

        jMenuTABLA_CORREDORES.setText("Tabla De Corredores");

        jMenuIrTablaCorredores.setText("Ir a la Tabla de Corredores");
        jMenuIrTablaCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIrTablaCorredoresActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuIrTablaCorredores);

        jMenuIrCrearCorredor.setText("Ir a Crear Corredor");
        jMenuIrCrearCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIrCrearCorredorActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuIrCrearCorredor);

        jMenuItemModificarCorredor.setText("Modificar Corredor");
        jMenuItemModificarCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarCorredorActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuItemModificarCorredor);

        jMenuBar1.add(jMenuTABLA_CORREDORES);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDNICorredor)
                            .addComponent(jTextFieldNombreCorredor)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSpinnerFecha_nacCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 293, Short.MAX_VALUE))
                            .addComponent(jTextFieldTelefonoCorredor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDireccionCorredor))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jButtonModificarCorredor)
                        .addGap(74, 74, 74)
                        .addComponent(jButtonVolver)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombreCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldDNICorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jSpinnerFecha_nacCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldDireccionCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTelefonoCorredor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificarCorredor)
                    .addComponent(jButtonVolver))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void asignarParametros(Corredor corredor){
       jTextFieldNombreCorredor.setText(corredor.getNombre());
       jTextFieldDNICorredor.setText(corredor.getDNI());
       jSpinnerFecha_nacCorredor.setValue(corredor.getFecha_nac());
       jTextFieldDireccionCorredor.setText(corredor.getDireccion());
       jTextFieldTelefonoCorredor.setText(corredor.getTelefono()); 
       
       idAnterior=corredor.getNombre();
    }
    
    public void modificar(){
        String nombre = jTextFieldNombreCorredor.getText();
        String DNI = jTextFieldDNICorredor.getText();
        Date fecha = (Date)jSpinnerFecha_nacCorredor.getValue();
        String direccion = jTextFieldDireccionCorredor.getText();
        String telefono = jTextFieldTelefonoCorredor.getText();

        Corredor corredor = new Corredor(nombre, DNI, fecha, direccion, telefono);
            
        List<Corredor> listaCorredor = logicaNegocioCorredor.getListaCorredor();
        for(int i=0 ; i<listaCorredor.size(); i++){
            if(listaCorredor.get(i).toArrayString()[0] == idAnterior){
                  logicaNegocioCorredor.actualizarCorredor(corredor, i);
            }
        }
         
        setVisible(false);
    }
    
    //ACCIONES
    private void jMenuItemModificarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarCorredorActionPerformed
        modificar();
    }//GEN-LAST:event_jMenuItemModificarCorredorActionPerformed

    private void jButtonModificarCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarCorredorActionPerformed
       modificar();
    }//GEN-LAST:event_jButtonModificarCorredorActionPerformed

    private void jMenuIrTablaCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIrTablaCarrerasActionPerformed
          List<Corredor> listaCorredor = logicaNegocioCorredor.getListaCorredor();
        
        if(listaCorredor.size()==0 || listaCorredor.get(0).getNombre()==""){
            JOptionPane.showMessageDialog(this, "No puedes crear una carrera sin corredores", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            CarreraTabla carreraTabla = new CarreraTabla(new javax.swing.JFrame(), true);
            carreraTabla.setVisible(true);
        }

      
    }//GEN-LAST:event_jMenuIrTablaCarrerasActionPerformed

    private void jMenuIrCrearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIrCrearCarreraActionPerformed
          List<Corredor> listaCorredor = logicaNegocioCorredor.getListaCorredor();
        
        if(listaCorredor.size()==0 || listaCorredor.get(0).getNombre()==""){
            JOptionPane.showMessageDialog(this, "No puedes crear una carrera sin corredores", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
            CarreraCrear carreraCrear = new CarreraCrear(new javax.swing.JFrame(), true);
            carreraCrear.setVisible(true);
        }

       
    }//GEN-LAST:event_jMenuIrCrearCarreraActionPerformed

    private void jMenuIrTablaCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIrTablaCorredoresActionPerformed
        CorredorTabla corredorTabla = new CorredorTabla(new javax.swing.JFrame(), true);
       corredorTabla.setVisible(true);
    }//GEN-LAST:event_jMenuIrTablaCorredoresActionPerformed

    private void jMenuIrCrearCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIrCrearCorredorActionPerformed
       CorredorCrear corredorCrear = new CorredorCrear(new javax.swing.JFrame(), true);
       corredorCrear.setVisible(true);
    }//GEN-LAST:event_jMenuIrCrearCorredorActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
         this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorredorModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorredorModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorredorModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorredorModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CorredorModificar dialog = new CorredorModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarCorredor;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIrCrearCarrera;
    private javax.swing.JMenuItem jMenuIrCrearCorredor;
    private javax.swing.JMenuItem jMenuIrTablaCarreras;
    private javax.swing.JMenuItem jMenuIrTablaCorredores;
    private javax.swing.JMenuItem jMenuItemModificarCorredor;
    private javax.swing.JMenu jMenuTABLA_CARRERAS;
    private javax.swing.JMenu jMenuTABLA_CORREDORES;
    private javax.swing.JSpinner jSpinnerFecha_nacCorredor;
    private javax.swing.JTextField jTextFieldDNICorredor;
    private javax.swing.JTextField jTextFieldDireccionCorredor;
    private javax.swing.JTextField jTextFieldNombreCorredor;
    private javax.swing.JTextField jTextFieldTelefonoCorredor;
    // End of variables declaration//GEN-END:variables
}
