/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_carreras_deportivasfinal.GUI.Carreras.CorredoresCarrera;


import gestion_carreras_deportivasfinal.DTO.Carrera;
import gestion_carreras_deportivasfinal.DTO.Componente.pruebarelojdigital.Reloj;
import gestion_carreras_deportivasfinal.DTO.Corredor;
import gestion_carreras_deportivasfinal.DTO.LogicaNegocioCarrera;
import gestion_carreras_deportivasfinal.DTO.LogicaNegocioCorredor;
import gestion_carreras_deportivasfinal.GUI.Carreras.CarreraCrear;
import gestion_carreras_deportivasfinal.GUI.Corredores.CorredorCrear;
import gestion_carreras_deportivasfinal.GUI.Corredores.CorredorTabla;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author David
 */
public class CorredoresDeCarreraTabla extends javax.swing.JDialog {

    private LogicaNegocioCorredor logicaNegocioCorredor;
    private LogicaNegocioCarrera logicaNegocioCarrera;
    private static List<Corredor> listaCorredoresDeCarrera;
    public static int posicion;
 
    public static Carrera carrera;
    /**
     * Creates new form CorredoresDeCarreraTabla
     */
    public CorredoresDeCarreraTabla(java.awt.Frame parent, boolean modal, Carrera carrera, int posicion) {
        super(parent, modal);
        initComponents();
        List<Corredor> listaCorredoresDeCarrera = new ArrayList<Corredor>(carrera.getMapaCorredor().keySet());
        this.listaCorredoresDeCarrera=listaCorredoresDeCarrera;
        this.posicion=posicion;
        this.carrera=carrera;
        
         List<Corredor> listaCorredor = LogicaNegocioCorredor.getListaCorredor();
        
        DefaultListModel model = new DefaultListModel<>();
           for(int i=0 ; i<listaCorredor.size(); i++){
           model.addElement(listaCorredor.get(i).toArrayString()[0]);
           }
       
           JList listaCorredores = jListListaCorredores; 
           listaCorredores.setModel(model);
 
           
        refrescarTabla(listaCorredoresDeCarrera);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIniciarCarrera = new javax.swing.JButton();
        jButtonCrear = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCorredoresCarrera = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListListaCorredores = new javax.swing.JList<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTABLA_CARRERAS = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItemCrearCarrera = new javax.swing.JMenuItem();
        jMenuTABLA_CORREDORES = new javax.swing.JMenu();
        jMenuIrTablaCorredores = new javax.swing.JMenuItem();
        jMenuItemCrearCorredor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButtonIniciarCarrera.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonIniciarCarrera.setText("Iniciar Carrera");
        jButtonIniciarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarCarreraActionPerformed(evt);
            }
        });

        jButtonCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCrear.setText("Asignar Corredor");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonBorrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBorrar.setText("Borrar Corredor");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jTableCorredoresCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCorredoresCarrera);

        jScrollPane2.setViewportView(jListListaCorredores);

        jMenuTABLA_CARRERAS.setText("Tabla De Carreras");

        jMenuItem1.setText("Ir a Tabla Carreras");
        jMenuTABLA_CARRERAS.add(jMenuItem1);

        jMenuItemCrearCarrera.setText("Ir a Crear Carrera");
        jMenuItemCrearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearCarreraActionPerformed(evt);
            }
        });
        jMenuTABLA_CARRERAS.add(jMenuItemCrearCarrera);

        jMenuBar1.add(jMenuTABLA_CARRERAS);

        jMenuTABLA_CORREDORES.setText("Tabla De Corredores");

        jMenuIrTablaCorredores.setText("Ir a la Tabla de Corredores");
        jMenuIrTablaCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIrTablaCorredoresActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuIrTablaCorredores);

        jMenuItemCrearCorredor.setText("Ir a Crear Corredor");
        jMenuItemCrearCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearCorredorActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuItemCrearCorredor);

        jMenuBar1.add(jMenuTABLA_CORREDORES);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonBorrar)
                                .addGap(43, 43, 43)
                                .addComponent(jButtonVolver)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCrear)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jButtonIniciarCarrera)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonCrear))
                .addGap(18, 18, 18)
                .addComponent(jButtonIniciarCarrera)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //ACCIONES
      public void aniadirCorredor(){
       String NombreCorredor = jListListaCorredores.getSelectedValue();
       List<Corredor> listaCorredor = logicaNegocioCorredor.getListaCorredor();
       List<Carrera> listaCarrera = logicaNegocioCarrera.getListaCarrera();
 
         for(Corredor corredor : listaCorredor){
             if(corredor.getNombre().equals(NombreCorredor)){
                carrera.getMapaCorredor().put(corredor, carrera.getMapaCorredor().size()+1);
            }
        }
    
    }
    
    
    public void borrarCorredor(){
      DefaultTableModel dtm = (DefaultTableModel)jTableCorredoresCarrera.getModel();
       List<Corredor> listaCorredor = this.listaCorredoresDeCarrera;
       
       //CORREDOR DE ESA LINEA  
       int row = jTableCorredoresCarrera.getSelectedRow();
       String nombre = jTableCorredoresCarrera.getModel().getValueAt(row, 0).toString();
  
       int resultado = JOptionPane.showConfirmDialog(this, "¿Quieres borrar este corredor?", "Corredor",JOptionPane.YES_NO_OPTION);
       if(resultado == JOptionPane.YES_OPTION){
           JOptionPane.showMessageDialog(this, "Borramos", "Corredor", JOptionPane.INFORMATION_MESSAGE);
           listaCorredor.forEach((corredor) -> {
               if(corredor.getNombre().equals(nombre)){
               carrera.getMapaCorredor().remove(corredor);
                }
          }); 

       }
       else if (resultado == JOptionPane.NO_OPTION){
           JOptionPane.showMessageDialog(this, "No Borramos", "Corredor", JOptionPane.INFORMATION_MESSAGE);   
       }
        
    }
    private void refrescarTabla(List<Corredor> lista){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre", "DNI", "Fecha", "Direccion", "Telefono"});

        List<Corredor> listaCorredorAsignados=lista;
  
        for(Corredor corredor : listaCorredorAsignados){
            dtm.addRow(corredor.toArrayString());
        }
        jTableCorredoresCarrera.setModel(dtm);
        
         //pal default
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(dtm);
        jTableCorredoresCarrera.setRowSorter(sorter);
        
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(2,SortOrder.ASCENDING));
       
        sorter.setSortKeys(sortKeys);
        
          List<Corredor> listaCorredor = logicaNegocioCorredor.getListaCorredor();
        
           DefaultListModel model = new DefaultListModel<>();
           for(int i=0 ; i<listaCorredor.size(); i++){
           model.addElement(listaCorredor.get(i).toArrayString()[0]);
           } 
       
           
    }
    
    //IR A OTRAS VENTANAS
    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        aniadirCorredor();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jMenuItemCrearCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearCorredorActionPerformed
        CorredorCrear corredorCrear = new CorredorCrear(new javax.swing.JFrame(), true);
        corredorCrear.setVisible(true);
    }//GEN-LAST:event_jMenuItemCrearCorredorActionPerformed

    private void jMenuIrTablaCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIrTablaCorredoresActionPerformed
        CorredorTabla corredorTabla = new CorredorTabla(new javax.swing.JFrame(), true);
        corredorTabla.setVisible(true);
    }//GEN-LAST:event_jMenuIrTablaCorredoresActionPerformed

    private void jMenuItemCrearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearCarreraActionPerformed
        CarreraCrear carreraCrear = new CarreraCrear(new javax.swing.JFrame(), true);
        carreraCrear.setVisible(true);
    }//GEN-LAST:event_jMenuItemCrearCarreraActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        borrarCorredor();
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtonIniciarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarCarreraActionPerformed
        Reloj reloj = new Reloj(new javax.swing.JFrame(), true);
        reloj.setVisible(true);
    }//GEN-LAST:event_jButtonIniciarCarreraActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorredoresDeCarreraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorredoresDeCarreraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorredoresDeCarreraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorredoresDeCarreraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CorredoresDeCarreraTabla dialog = new CorredoresDeCarreraTabla(new javax.swing.JFrame(), true, carrera, posicion);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonIniciarCarrera;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JList<String> jListListaCorredores;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIrTablaCorredores;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCrearCarrera;
    private javax.swing.JMenuItem jMenuItemCrearCorredor;
    private javax.swing.JMenu jMenuTABLA_CARRERAS;
    private javax.swing.JMenu jMenuTABLA_CORREDORES;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCorredoresCarrera;
    // End of variables declaration//GEN-END:variables
}
