/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion_carreras_deportivasfinal.GUI.Carreras;

import gestion_carreras_deportivasfinal.DTO.Carrera;
import gestion_carreras_deportivasfinal.DTO.LogicaNegocioCarrera;
import gestion_carreras_deportivasfinal.GUI.Carreras.CorredoresCarrera.CorredoresDeCarreraTabla;
import gestion_carreras_deportivasfinal.GUI.Corredores.CorredorCrear;
import gestion_carreras_deportivasfinal.GUI.Corredores.CorredorModificar;
import gestion_carreras_deportivasfinal.GUI.Corredores.CorredorTabla;
import gestion_carreras_deportivasfinal.GUI.PantallaPrincipal;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author David
 */
public class CarreraTabla extends javax.swing.JDialog {
 
    
    //SE AÑADE LAS LOGICAS DE NEGOCIO
     private LogicaNegocioCarrera logicaNegocioCarrera;
     
    /**
     * Creates new form CarreraTabla
     */
    public CarreraTabla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        refrescarTabla();
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarrera = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jButtonCrear = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonAsignarCorredores = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTABLA_CARRERAS = new javax.swing.JMenu();
        jMenuItemCrearCarrera = new javax.swing.JMenuItem();
        jMenuItemModificarCarrera = new javax.swing.JMenuItem();
        jMenuItemBorrarCarrera = new javax.swing.JMenuItem();
        jMenuTABLA_CORREDORES = new javax.swing.JMenu();
        jMenuIrTablaCorredores = new javax.swing.JMenuItem();
        jMenuItemCrearCorredor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCarrera);

        jButtonVolver.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonBorrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBorrar.setText("Borrar Carrera");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jButtonCrear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonCrear.setText("Crear Carrera");
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonModificar.setText("Modificar Carrera");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonAsignarCorredores.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonAsignarCorredores.setText("Asignar Corredores/Iniciar Carrera");
        jButtonAsignarCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAsignarCorredoresActionPerformed(evt);
            }
        });

        jMenuTABLA_CARRERAS.setText("Tabla De Carreras");

        jMenuItemCrearCarrera.setText("Ir a Crear Carrera");
        jMenuItemCrearCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearCarreraActionPerformed(evt);
            }
        });
        jMenuTABLA_CARRERAS.add(jMenuItemCrearCarrera);

        jMenuItemModificarCarrera.setText("Ir a Modificar Carrera");
        jMenuItemModificarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModificarCarreraActionPerformed(evt);
            }
        });
        jMenuTABLA_CARRERAS.add(jMenuItemModificarCarrera);

        jMenuItemBorrarCarrera.setText("Ir a Borrar Carrera");
        jMenuItemBorrarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBorrarCarreraActionPerformed(evt);
            }
        });
        jMenuTABLA_CARRERAS.add(jMenuItemBorrarCarrera);

        jMenuBar1.add(jMenuTABLA_CARRERAS);

        jMenuTABLA_CORREDORES.setText("Tabla De Corredores");

        jMenuIrTablaCorredores.setText("Ir a la Tabla de Corredores");
        jMenuIrTablaCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIrTablaCorredoresActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuIrTablaCorredores);

        jMenuItemCrearCorredor.setText("Ir a Crear Corredor");
        jMenuItemCrearCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearCorredorActionPerformed(evt);
            }
        });
        jMenuTABLA_CORREDORES.add(jMenuItemCrearCorredor);

        jMenuBar1.add(jMenuTABLA_CORREDORES);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jButtonCrear))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(215, 215, 215)
                                .addComponent(jButtonVolver)))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonModificar)
                            .addComponent(jButtonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAsignarCorredores, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrear)
                    .addComponent(jButtonModificar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVolver)
                    .addComponent(jButtonBorrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jButtonAsignarCorredores)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refrescarTabla(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(new String[]{"Nombre", "Fecha", "Lugar", "Numero_Max", "Mapa_Corredor"});
        
        List<Carrera> listaCarrera = logicaNegocioCarrera.getListaCarrera();
        for(Carrera carrera : listaCarrera){
            dtm.addRow(carrera.toArrayString());
        }
        jTableCarrera.setModel(dtm);
        
        //SORTER
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<DefaultTableModel>(dtm);
        jTableCarrera.setRowSorter(sorter);
        
        List<RowSorter.SortKey> sortKeys = new ArrayList<>();
        sortKeys.add(new RowSorter.SortKey(2,SortOrder.ASCENDING));
       
        sorter.setSortKeys(sortKeys);
    }

     public void iractualizarCarrera(){
       int row = jTableCarrera.getSelectedRow();
       String nombre = jTableCarrera.getModel().getValueAt(row, 0).toString();
       List<Carrera> listaCarrera = logicaNegocioCarrera.getListaCarrera();
       Carrera carrera=null;
       
       for(Carrera carrera2 : listaCarrera){
        if(carrera2.getNombre().equals(nombre)){
             carrera=carrera2;
        }     
       }
       
        CarreraModificar carreraModificar = new CarreraModificar(new javax.swing.JFrame(), true);
        carreraModificar.asignarParametros(carrera); 
        carreraModificar.setVisible(true);
    }
     
    public void borrar(){
       int row = jTableCarrera.getSelectedRow();
       String nombre = jTableCarrera.getModel().getValueAt(row, 0).toString();
       List<Carrera> listaCarreras = logicaNegocioCarrera.getListaCarrera();
       
       int resultado = JOptionPane.showConfirmDialog(this, "¿Quieres borrar esta carrera?", "Carrera",JOptionPane.YES_NO_OPTION);
       if(resultado == JOptionPane.YES_OPTION){
          JOptionPane.showMessageDialog(this, "Borramos", "Carrera", JOptionPane.INFORMATION_MESSAGE);
 
           for(int i=0 ; i<listaCarreras.size(); i++){
            if(listaCarreras.get(i).toArrayString()[0].equals(nombre) ){
                  logicaNegocioCarrera.borrarCarrera(i);
            }
        }
          DefaultTableModel dtm = (DefaultTableModel)jTableCarrera.getModel();
          dtm.removeRow(row);
          jTableCarrera.setModel(dtm);
       }
       else if (resultado == JOptionPane.NO_OPTION){
           JOptionPane.showMessageDialog(this, "No Borramos", "Carrera", JOptionPane.INFORMATION_MESSAGE);   
       } 
    }
    
    //ACCIONES
    private void jMenuItemBorrarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBorrarCarreraActionPerformed
        borrar();
    }//GEN-LAST:event_jMenuItemBorrarCarreraActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        borrar();
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jMenuItemCrearCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearCarreraActionPerformed
       CarreraCrear carreraCrear = new CarreraCrear(new javax.swing.JFrame(), true);
       carreraCrear.setVisible(true);
       refrescarTabla();
    }//GEN-LAST:event_jMenuItemCrearCarreraActionPerformed

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
       CarreraCrear carreraCrear = new CarreraCrear(new javax.swing.JFrame(), true);
       carreraCrear.setVisible(true);
       refrescarTabla();
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jMenuItemModificarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModificarCarreraActionPerformed
       iractualizarCarrera();
       refrescarTabla();
    }//GEN-LAST:event_jMenuItemModificarCarreraActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
       iractualizarCarrera();
       refrescarTabla();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jMenuIrTablaCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIrTablaCorredoresActionPerformed
       CorredorTabla corredorTabla = new CorredorTabla(new javax.swing.JFrame(), true);
       corredorTabla.setVisible(true);
    }//GEN-LAST:event_jMenuIrTablaCorredoresActionPerformed

    private void jMenuItemCrearCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearCorredorActionPerformed
       CorredorCrear corredorCrear = new CorredorCrear(new javax.swing.JFrame(), true);
       corredorCrear.setVisible(true);
    }//GEN-LAST:event_jMenuItemCrearCorredorActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAsignarCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAsignarCorredoresActionPerformed
       int row = jTableCarrera.getSelectedRow();
       String nombre = jTableCarrera.getModel().getValueAt(row, 0).toString();
       List<Carrera> listaCarrera = logicaNegocioCarrera.getListaCarrera(); 
       Carrera carrera=null;
       int g=0;
       for(Carrera carrera2 : listaCarrera){
        if(carrera2.getNombre().equals(nombre)){
            carrera=carrera2;
        }     
        g++;
       } 
        
       CorredoresDeCarreraTabla corredoresCarrera = new CorredoresDeCarreraTabla(new javax.swing.JFrame(), true,carrera, g);
       corredoresCarrera.setVisible(true);
    }//GEN-LAST:event_jButtonAsignarCorredoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarreraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarreraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarreraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarreraTabla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CarreraTabla dialog = new CarreraTabla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAsignarCorredores;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIrTablaCorredores;
    private javax.swing.JMenuItem jMenuItemBorrarCarrera;
    private javax.swing.JMenuItem jMenuItemCrearCarrera;
    private javax.swing.JMenuItem jMenuItemCrearCorredor;
    private javax.swing.JMenuItem jMenuItemModificarCarrera;
    private javax.swing.JMenu jMenuTABLA_CARRERAS;
    private javax.swing.JMenu jMenuTABLA_CORREDORES;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCarrera;
    // End of variables declaration//GEN-END:variables
}
